### ISSUE TITLE
Accept multiple subscription on a single socket

### ISSUE THREAD

**Issue by EricGarnier** [JKorf/CoinEx.Net#59]
Hi @JKorf 
I notice that for CoinEx, you forbid the setting of SocketSubscriptionsCombineTarget.
However, this should work according to CoinEx documentation.

Do you encounter specific problem in this area ?

Thanks.
Eric

**Comment by JKorf** [comment]
Hi Eric, This is because the server doesn't allow multiple subscriptions for different symbols. If I don't set the combine target to 1 and try to subscribe to 2 symbols like this:
````csharp
var x3 = await coinexSocket.SpotStreams.SubscribeToTickerUpdatesAsync("BTCUSDT", data =>
{
    Console.WriteLine("Kline2");
});
var x2 = await coinexSocket.SpotStreams.SubscribeToTickerUpdatesAsync("ETHUSDT", data =>
{
    Console.WriteLine("Kline1");
});
````
It will only give updates for the last subscription. Like this it only gives updates for ETHUSDT, and if I swap them only for BTCUSDT. 

https://github.com/coinexcom/coinex_exchange_api/wiki/041request_description also mentiones that multiple markets are not supported, even though it's a bit cryptic: `Not support mulit-market in websocket subscription.`
